#!/usr/bin/env python

# This is a small example program intended to demonstrate
# how the pb-routines from the ECMWF BUFR library
# may be used.

# For details on the revision history, refer to the log-notes in
# the mercurial revisioning system hosted at google code.
#
# Written by: J. de Kloe, KNMI, Initial version 22-Jan-2010
#
# License: GPL v2.

import os          # import os functionality
import numpy as np # import numerical capabilities

# import the python file defining the BUFRInterfaceECMWF class
from pybufr_ecmwf import BUFRInterfaceECMWF

print "-"*50
print "pb usage example"
print "-"*50

# Note that this step is only added here to build the interface module
# ecmwfbufr.so. If you already have it compiled and installed
# you can skip this step. 
#
# instantiate the BUFRInterfaceECMWF class, and build library if needed
# the different examples illustrate how you can pass your preferred
# fortran compiler (and library path if needed) to this module, which
# will be used for compilation of the BUFR library itself and also
# for the fortran wrapper code generated by f2py.
BI = BUFRInterfaceECMWF(verbose=True)
#BI = BUFRInterfaceECMWF(verbose=True,debug_f2py_c_api=True)
#BI = BUFRInterfaceECMWF(verbose=True,preferred_fortran_compiler='gfortran')
#BI = BUFRInterfaceECMWF(verbose=True,
#                        fortran_compiler="/home/jos/bin/gfortran_personal",
#                        fortran_ld_library_path="/home/jos/bin/gcc-trunk/lib64",
#                        fortran_flags="-fno-second-underscore -fPIC")
#BI = BUFRInterfaceECMWF(verbose=True,
#                        fortran_compiler="/home/jos/bin/g95_32",
#                        fortran_flags="-fno-second-underscore -fPIC -i4 -r8")
#BI = BUFRInterfaceECMWF(verbose=True,
#                        fortran_compiler="/home/jos/bin/g95_64",
#                        fortran_flags="-fno-second-underscore -fPIC -i4 -r8")

# import the raw wrapper interface to the ECMWF BUFR library
import ecmwfbufr

# NOTE: this testfile: Testfile3CorruptedMsgs.BUFR
# hold 3 copies of Testfile.BUFR catted together, and
# was especially modified using hexedit to have
# false end markers (7777) halfway the 2nd and 3rd
# message. These messages are therefore corrupted and
# decoding them will probably result in garbage, but they
# are very usefull to test the BUFRFile.split() method.

# define the input test filename
input_test_bufr_file = 'Testfile3CorruptedMsgs.BUFR'

# pbopen test

c_file_unit     = 0
bufr_error_flag = 0
print "input_test_bufr_file = ["+input_test_bufr_file+"]"
print "calling: ecmwfbufr.pbopen()"
(c_file_unit,bufr_error_flag) = ecmwfbufr.pbopen(input_test_bufr_file,'R')

# this will be the call if intent(inplace) is used in the 
# insert_pb_interface_definition method of BUFRInterfaceECMWF
# in stead of intent(in) and intent(out):
# ecmwfbufr.pbopen(c_file_unit,input_test_bufr_file,
#                  'R',bufr_error_flag)

print "c_file_unit = ",c_file_unit
print "bufr_error_flag = ",bufr_error_flag

# pbbufr test

buffer_size_words = 12000
buffer_size_bytes = buffer_size_words/4

for i in range(4):
    msg_size_bytes = 0
    bufr_error_flag = 0
    print "calling: ecmwfbufr.pbbufr()"
    buffer = np.zeros(buffer_size_words,dtype=np.int)
    ecmwfbufr.pbbufr(c_file_unit,buffer,buffer_size_bytes,
                     msg_size_bytes,bufr_error_flag)
    print "BUFR message: ",i

    # retrieve these sizes manually, since they seem not
    # provided by the current interface (don't know why)
    msg_size_words = len(np.where(buffer>0)[0])
    msg_size_bytes = msg_size_words*4
    print "msg_size_bytes = ",msg_size_bytes
    print "buffer[0:4] = ",buffer[0:4]
    print "bufr_error_flag = ",bufr_error_flag

    # warning: on my system only the first 36 bytes (9 words)
    # of each BUFR message are read in this way, so for now
    # this pb-interface seems useless, even if it compiles
    # and runs without explicit errors ....

# pbclose test

bufr_error_flag = 0
print "calling: ecmwfbufr.pbclose()"
ecmwfbufr.pbclose(c_file_unit,bufr_error_flag)
print "bufr_error_flag = ",bufr_error_flag

print "-"*50
print "done"
print "-"*50
